### PR TITLE
Fix false-positive when the `<!Entity>` tag contains markup

### LINKED ISSUE #23: Detection fails on svg but don't know why
is-svg returns false for the following svg:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"
[ <!ENTITY Smile "
<rect x='.5' y='.5' width='29' height='39' fill='black' stroke='red'/>
<g transform='translate(0, 5)'>
<circle cx='15' cy='15' r='10' fill='yellow'/>
<circle cx='12' cy='12' r='1.5' fill='black'/>
<circle cx='17' cy='12' r='1.5' fill='black'/>
<path d='M 10 19 A 8 8 0 0 0 20 19' stroke='black' stroke-width='2'/>
</g>
">
<!ENTITY Viewport1 "<rect x='.5' y='.5' width='49' height='29'
fill='none' stroke='blue'/>">
<!ENTITY Viewport2 "<rect x='.5' y='.5' width='29' height='59'
fill='none' stroke='blue'/>">
]>
<svg width="850px" height="700px" version="1.1"
     xmlns="http://www.w3.org/2000/svg">
  <g transform="matrix(16,0,0,16,0,0)">
  &Smile;
  </g>
</svg>
```

It's a SVG I took from the internet, can you tell me why this is an invalid SVG?

### PR DESCRIPTION
**Pull request by eluisfonseca**
Fixes #23 
Fixes isSvg returning false for valid svg, whenever they included markup inside an <Entity> tag
It now searches for <!Entity> tags and clears them of markup, before applying the usual regex.
Also added an svg with an appropriate example to the valid svg tests.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -15,9 +15,33 @@ const isBinary = buffer => {
 	return false;
 };
 
+const cleanEntities = svg => {
+	const entityRegex = /\s*<!Entity\s+\S*\s*(?:"|')[^"]+(?:"|')\s*>/img;
```
Comment (sindresorhus) [inline index.js]: I think you're over-complicating it. We don't really use the `<!Entity` tag for detecting SVG, so we can just remove the whole tag.

File: test.js [hunk 2]
```diff
@@ -9,6 +9,7 @@ test('valid SVGs', t => {
...
 	t.true(isSvg('<?xml version="1.0" encoding="utf-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [<!ENTITY ns_flows "http://ns.adobe.com/Flows/1.0/">]><svg></svg>'));
 	t.true(isSvg('<?xml version="1.0" encoding="utf-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [ <!ENTITY ns_flows "http://ns.adobe.com/Flows/1.0/"> <!ENTITY ns_custom "http://ns.adobe.com/GenericCustomNamespace/1.0/"> ]><svg></svg>'));
+	t.true(isSvg('<?xml version="1.0" encoding="utf-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [ <!ENTITY ns_flows "http://ns.adobe.com/Flows/1.0/"> <!ENTITY Smile " <rect x=\'.5\' y=\'.5\' width=\'29\' height=\'39\' fill=\'black\' stroke=\'red\'/> <g transform=\'translate(0, 5)\'> <circle cx=\'15\' cy=\'15\' r=\'10\' fill=\'yellow\'/><circle cx=\'12\' cy=\'12\' r=\'1.5\' fill=\'black\'/><circle cx=\'17\' cy=\'12\' r=\'1.5\' fill=\'black\'/><path d=\'M 10 19 L 15 23 20 19\' stroke=\'black\' stroke-width=\'2\'/></g>"> ]><svg></svg>'));
```
Comment (sindresorhus) [inline test.js]: Move this to a separate test method.

**Comment by sindresorhus** [comment]
The PR title should say what it fixes more clearly. And you should use `Fixes #23` GitHub syntax so the issue is closed when the PR is merged.

I would recommend reading https://github.com/tiimgreen/github-cheat-sheet#readme

File: index.js (hunk 1 above)
Comment (eluisfonseca) [reply index.js]: Oh, sorry. I just chose to keep the entity tag because sometimes when you define an entity id (Smile, in this example) you can reference it on the svg code and it must exist for the svg to be valid. I'll remove the entities altogether.

File: test.js (hunk 2 above)
Comment (eluisfonseca) [reply test.js]: done

File: index.js (hunk 1 above)
Comment (sindresorhus) [reply index.js]: The regex and code could still be simplified. `.replace` supports a callback you could use instead of both `.match` and `.replace.`.

Comment (sindresorhus) [reply index.js]: Actually, you can just use normal replace with:

```suggestion
	const entityRegex = /<!Entity[^>]*?>/ig;
```

Comment (eluisfonseca) [reply index.js]: You are right. I replaced match with a single normal replace, but I had to keep my previous regex.
The tests were failing since`/<!Entity[^>]*?>/ig` would only match up until the first markup tag closure. Meaning that if that any subsequent markup tags would not be removed and the match would fail as before.

File: index.js [hunk 3]
```diff
@@ -15,9 +15,16 @@ const isBinary = buffer => {
...
+	// Remove entities
+	svg = svg.replace(entityRegex, '');
+	return svg;
```
Comment (sindresorhus) [inline index.js]:
```suggestion
	return svg.replace(entityRegex, '');
```

File: test.js [hunk 4]
```diff
@@ -50,3 +50,7 @@ test('supports non-english characters', t => {
 
 	</svg>`));
 });
+
+test('support markup inside Entity tags', t => {
+	t.true(isSvg('<?xml version="1.0" encoding="utf-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [ <!ENTITY ns_flows "http://ns.adobe.com/Flows/1.0/"> <!ENTITY Smile " <rect x=\'.5\' y=\'.5\' width=\'29\' height=\'39\' fill=\'black\' stroke=\'red\'/> <g transform=\'translate(0, 5)\'> <circle cx=\'15\' cy=\'15\' r=\'10\' fill=\'yellow\'/><circle cx=\'12\' cy=\'12\' r=\'1.5\' fill=\'black\'/><circle cx=\'17\' cy=\'12\' r=\'1.5\' fill=\'black\'/><path d=\'M 10 19 L 15 23 20 19\' stroke=\'black\' stroke-width=\'2\'/></g>"> ]><svg></svg>'));
```
Comment (sindresorhus) [inline test.js]: I think it could be useful with some more assertions to ensure the entity regex covers all the ways Entity could be used and what it could contain.

File: index.js (hunk 3 above)
Comment (eluisfonseca) [reply index.js]: Done

File: test.js (hunk 4 above)
Comment (eluisfonseca) [reply test.js]: There were already some tests covering regular entity tags on validity tests. 
I added some regarding markup only:
- svg with single entity tag with markup;
- svg with multiple entity tags (no-markup and with markup)
- svg with multiple entity tags both with markup)

**Comment by sindresorhus** [comment]
This looks great now. Thanks for all your hard work on this PR 🙌
