### PR TITLE
Fix false-negative with linebreaks inside the SVG tag

### LINKED ISSUE #28: False negativ
```javascript
const isSvg = require("is-svg")

// svg from 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Biochem_reaction_arrow_forward_NNNN_horiz_med.svg'

const svg = `
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
xmlns="http://www.w3.org/2000/svg"
width="75"
height="75"
version="1.1"
><g>
<path
style="fill:#000000;stroke:none"
d="m 67,34.5 0,2 -67,0 0,2 67,0 0,2 8,-3 -8,-3 z"
/></g>
</svg>
`

isSvg(svg) // false but should be true
```

line breaks are the problem I think.

### PR DESCRIPTION
**Pull request by StephanHoyer**
Fixes #28

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -20,6 +20,13 @@ test('valid SVGs', t => {
 <svg version="1.1">
 </svg>
 `));
+	t.true(isSvg(`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
+<svg
+xmlns="http://www.w3.org/2000/svg"
+width="75"
+height="75"
+version="1.1"
+></svg>`));
```
Comment (sindresorhus) [inline test.js:29]: This test passes on the `main` branch.

Comment (StephanHoyer) [reply test.js:29]: I just tried it again, does not work for me. I also tried it on runkit, still does not work.

https://runkit.com/embed/r74bv6am4lp6
